export const FETCH_MEALS_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_RECIPES_FAILURE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
